#pragma once
#include "stdafx.h"

#define N_GRAPHS 15

#define GRAPH_SEPARATORS 2,\
	FST::NODE(13, FST::RELATION(';',1), FST::RELATION('=',1),\
				  FST::RELATION(',',1), FST::RELATION('{',1),\
				  FST::RELATION('}',1), FST::RELATION('(',1),\
				  FST::RELATION(')',1), FST::RELATION('*',1),\
				  FST::RELATION(']',1), FST::RELATION('[',1),\
				  FST::RELATION('+',1), FST::RELATION('-',1),\
					FST::RELATION('.',1), FST::RELATION('!',1),\
				  FST::RELATION('/',1)),\
	FST::NODE()

#define GRAPH_ROOT 5, \
	FST::NODE(1,FST::RELATION('r',1)),\
	FST::NODE(1,FST::RELATION('o',2)),\
	FST::NODE(1,FST::RELATION('o',3)),\
	FST::NODE(1,FST::RELATION('t',4)),\
	FST::NODE()


#define GRAPH_POWER 6,\
	FST::NODE(1,FST::RELATION('p',1)),\
	FST::NODE(1,FST::RELATION('o',2)),\
	FST::NODE(1,FST::RELATION('w',3)),\
	FST::NODE(1,FST::RELATION('e',4)),\
    FST::NODE(1,FST::RELATION('r',5)),\
	FST::NODE()

#define GRAPH_EMatLib 8,\
	FST::NODE(1,FST::RELATION('E',1)),\
	FST::NODE(1,FST::RELATION('M',2)),\
	FST::NODE(1,FST::RELATION('a',3)),\
	FST::NODE(1,FST::RELATION('t',4)),\
	FST::NODE(1,FST::RELATION('L',5)),\
	FST::NODE(1,FST::RELATION('i',6)),\
	FST::NODE(1,FST::RELATION('b',7)),\
	FST::NODE()


#define GRAPH_FORWARD_SLASH 2,\
	FST::NODE(1,FST::RELATION('/',1)),\
	FST::NODE()

#define GRAPH_NUMBER_LITERAL IT::INT, 2, \
	FST::NODE(10,FST::RELATION('0',1),FST::RELATION('1',1),\
				FST::RELATION('3',1),FST::RELATION('2',1),\
				FST::RELATION('5',1),FST::RELATION('4',1),\
				FST::RELATION('7',1),FST::RELATION('6',1),\
				FST::RELATION('8',1),FST::RELATION('9',1)),\
	FST::NODE(10,FST::RELATION('0',1),FST::RELATION('1',1),\
				FST::RELATION('3',1),FST::RELATION('2',1),\
				FST::RELATION('5',1),FST::RELATION('4',1),\
				FST::RELATION('7',1),FST::RELATION('6',1),\
				FST::RELATION('8',1),FST::RELATION('9',1))
//62
#define GRAPH_STRING_LITERAL IT::STR, 3, \
	FST::NODE(1, FST::RELATION('\'',1)),\
	FST::NODE(142, \
				FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1), \
				FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), \
				FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1), \
				FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1), \
				FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1), \
				FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1), \
				FST::RELATION('Y', 1), FST::RELATION('Z', 1), FST::RELATION('a', 1), FST::RELATION('b', 1), \
				FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1), \
				FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), \
				FST::RELATION('k', 1), FST::RELATION('l', 1), FST::RELATION('m', 1), FST::RELATION('n', 1), \
				FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1), \
				FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), \
				FST::RELATION('w', 1), FST::RELATION('x', 1), FST::RELATION('y', 1), FST::RELATION('z', 1), \
				FST::RELATION('1', 1), FST::RELATION('2', 1), FST::RELATION('3', 1), FST::RELATION('4', 1), \
				FST::RELATION('5', 1), FST::RELATION('6', 1), FST::RELATION('7', 1), FST::RELATION('8', 1), \
				FST::RELATION('9', 1), FST::RELATION('0', 1), \
				\
				FST::RELATION('À', 1), FST::RELATION('Á', 1), FST::RELATION('Â', 1), FST::RELATION('Ã', 1), \
				FST::RELATION('Ä', 1), FST::RELATION('Å', 1), FST::RELATION('¨', 1), FST::RELATION('Æ', 1), \
				FST::RELATION('Ç', 1), FST::RELATION('È', 1), FST::RELATION('É', 1), FST::RELATION('Ê', 1), \
				FST::RELATION('Ë', 1), FST::RELATION('Ì', 1), FST::RELATION('Í', 1), FST::RELATION('Î', 1), \
				FST::RELATION('Ï', 1), FST::RELATION('Ð', 1), FST::RELATION('Ñ', 1), FST::RELATION('Ò', 1), \
				FST::RELATION('Ó', 1), FST::RELATION('Ô', 1), FST::RELATION('Õ', 1), FST::RELATION('Ö', 1), \
				FST::RELATION('×', 1), FST::RELATION('Ø', 1), FST::RELATION('Ù', 1), FST::RELATION('Ú', 1), \
				FST::RELATION('Û', 1), FST::RELATION('Ü', 1), FST::RELATION('Ý', 1), FST::RELATION('Þ', 1), \
				FST::RELATION('ß', 1), FST::RELATION('à', 1), FST::RELATION('á', 1), FST::RELATION('â', 1), \
				FST::RELATION('ã', 1), FST::RELATION('ä', 1), FST::RELATION('å', 1), FST::RELATION('¸', 1), \
				FST::RELATION('æ', 1), FST::RELATION('ç', 1), FST::RELATION('è', 1), FST::RELATION('é', 1), \
				FST::RELATION('ê', 1), FST::RELATION('ë', 1), FST::RELATION('ì', 1), FST::RELATION('í', 1), \
				FST::RELATION('î', 1), FST::RELATION('ï', 1), FST::RELATION('ð', 1), FST::RELATION('ñ', 1), \
				FST::RELATION('ò', 1), FST::RELATION('ó', 1), FST::RELATION('ô', 1), FST::RELATION('õ', 1), \
				FST::RELATION('ö', 1), FST::RELATION('÷', 1), FST::RELATION('ø', 1), FST::RELATION('ù', 1), \
				FST::RELATION('ú', 1), FST::RELATION('û', 1), FST::RELATION('ü', 1), FST::RELATION('ý', 1), \
				FST::RELATION('þ', 1), FST::RELATION('ÿ', 1), FST::RELATION(' ', 1), FST::RELATION('.', 1),	\
				FST::RELATION(',', 1), FST::RELATION('?', 1), FST::RELATION('!', 1), FST::RELATION(';', 1), \
				FST::RELATION(':', 1), FST::RELATION('-', 1), FST::RELATION(')', 1), FST::RELATION('(', 1), \
				FST::RELATION('+', 1), FST::RELATION('*', 1), FST::RELATION('/', 1), FST::RELATION('\'', 2)), \
	FST::NODE()

#define GRAPH_MAIN IT::INT, 5, \
	FST::NODE(1,FST::RELATION('m',1)),\
	FST::NODE(1,FST::RELATION('a',2)),\
	FST::NODE(1,FST::RELATION('i',3)),\
	FST::NODE(1,FST::RELATION('n',4)),\
	FST::NODE()


#define GRAPH_INT IT::INT, 4, \
	FST::NODE(1,FST::RELATION('i',1)),\
	FST::NODE(1,FST::RELATION('n',2)),\
	FST::NODE(1,FST::RELATION('t',3)),\
	FST::NODE()

#define GRAPH_STRING IT::STR, 7, \
	FST::NODE(1,FST::RELATION('s',1)),\
	FST::NODE(1,FST::RELATION('t',2)),\
	FST::NODE(1,FST::RELATION('r',3)),\
	FST::NODE(1,FST::RELATION('i',4)),\
	FST::NODE(1,FST::RELATION('n',5)),\
	FST::NODE(1,FST::RELATION('g',6)),\
	FST::NODE()

#define GRAPH_FUNCTION 9, \
	FST::NODE(1, FST::RELATION('f', 1)),\
    FST::NODE(1, FST::RELATION('u', 2)),\
    FST::NODE(1, FST::RELATION('n', 3)),\
    FST::NODE(1, FST::RELATION('c', 4)),\
    FST::NODE(1, FST::RELATION('t', 5)),\
    FST::NODE(1, FST::RELATION('i', 6)),\
    FST::NODE(1, FST::RELATION('o', 7)),\
    FST::NODE(1, FST::RELATION('n', 8)),\
    FST::NODE()

#define GRAPH_RETURN 7, \
	FST::NODE(1,FST::RELATION('r',1)),\
	FST::NODE(1,FST::RELATION('e',2)),\
	FST::NODE(1,FST::RELATION('t',3)),\
	FST::NODE(1,FST::RELATION('u',4)),\
	FST::NODE(1,FST::RELATION('r',5)),\
	FST::NODE(1,FST::RELATION('n',6)),\
	FST::NODE()

#define GRAPH_TYPE 5, \
    FST::NODE(1, FST::RELATION('t', 1)),\
    FST::NODE(1, FST::RELATION('y', 2)),\
    FST::NODE(1, FST::RELATION('p', 3)),\
    FST::NODE(1, FST::RELATION('e', 4)),\
    FST::NODE()

#define GRAPH_OUTPUT 7,	\
	FST::NODE(1, FST::RELATION('o', 1)),\
    FST::NODE(1, FST::RELATION('u', 2)),\
    FST::NODE(1, FST::RELATION('t', 3)),\
	FST::NODE(1, FST::RELATION('p', 4)),\
    FST::NODE(1, FST::RELATION('u', 5)),\
	FST::NODE(1, FST::RELATION('t', 6)),\
    FST::NODE()

#define GRAPH_ID 2, \
	FST::NODE(52, \
				FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1), \
				FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), \
				FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1), \
				FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1), \
				FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1), \
				FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1), \
				FST::RELATION('Y', 1), FST::RELATION('Z', 1), FST::RELATION('a', 1), FST::RELATION('b', 1), \
				FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1), \
				FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), \
				FST::RELATION('k', 1), FST::RELATION('l', 1), FST::RELATION('m', 1), FST::RELATION('n', 1), \
				FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1), \
				FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), \
				FST::RELATION('w', 1), FST::RELATION('x', 1), FST::RELATION('y', 1), FST::RELATION('z', 1)),\
	FST::NODE(52, \
				FST::RELATION('A', 1), FST::RELATION('B', 1), FST::RELATION('C', 1), FST::RELATION('D', 1), \
				FST::RELATION('E', 1), FST::RELATION('F', 1), FST::RELATION('G', 1), FST::RELATION('H', 1), \
				FST::RELATION('I', 1), FST::RELATION('J', 1), FST::RELATION('K', 1), FST::RELATION('L', 1), \
				FST::RELATION('M', 1), FST::RELATION('N', 1), FST::RELATION('O', 1), FST::RELATION('P', 1), \
				FST::RELATION('Q', 1), FST::RELATION('R', 1), FST::RELATION('S', 1), FST::RELATION('T', 1), \
				FST::RELATION('U', 1), FST::RELATION('V', 1), FST::RELATION('W', 1), FST::RELATION('X', 1), \
				FST::RELATION('Y', 1), FST::RELATION('Z', 1), FST::RELATION('a', 1), FST::RELATION('b', 1), \
				FST::RELATION('c', 1), FST::RELATION('d', 1), FST::RELATION('e', 1), FST::RELATION('f', 1), \
				FST::RELATION('g', 1), FST::RELATION('h', 1), FST::RELATION('i', 1), FST::RELATION('j', 1), \
				FST::RELATION('k', 1), FST::RELATION('l', 1), FST::RELATION('m', 1), FST::RELATION('n', 1), \
				FST::RELATION('o', 1), FST::RELATION('p', 1), FST::RELATION('q', 1), FST::RELATION('r', 1), \
				FST::RELATION('s', 1), FST::RELATION('t', 1), FST::RELATION('u', 1), FST::RELATION('v', 1), \
				FST::RELATION('w', 1), FST::RELATION('x', 1), FST::RELATION('y', 1), FST::RELATION('z', 1))
